# Change these first
owner: datameet # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: DataMeet
    url: http://datameet.org/
  - name: Aadhaar Login
    url: https://ssup.uidai.gov.in/ssup/login.html
  - name: Passport User Registration Page
    url: https://portal2.passportindia.gov.in/AppOnlineProject/user/RegistrationBaseAction?request_locale=en
  - name: GST Login Page
    url : https://services.gst.gov.in/services/login
  - name: Karnataka State Natural Disaster Management Centre
    url: http://www.ksndmc.org/
  - name: Co-WIN Self Registration 
    url: https://selfregistration.cowin.gov.in/

status-website:
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # cname: projects.datameet.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "DataMeet **Upptime** is the monitoring page for various Indian Data Sites"
  introMessage: "We monitor multiple Indian Websites."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
